name: compile
on:
  push:
    branches:
      - docs
      - main
jobs:
  compile:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    concurrency:
      group: release
      cancel-in-progress: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          submodules: recursive

      - name: Compile latex approach
        uses: xu-cheng/latex-action@v2
        with:
          root_file: "report.tex"
          working_directory: "report/"
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode -shell-escape

      - name: Compile rbs
        uses: xu-cheng/latex-action@v2
        with:
          root_file: "requirements-breakdown-structure.tex"
          working_directory: "req-breakdown-structure/"
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode -shell-escape

      - name: Compile latex wbs
        uses: xu-cheng/latex-action@v2
        with:
          root_file: "work-breakdown-structure.tex"
          working_directory: "work-breakdown-structure/"
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode -shell-escape    
  
      - name: Compile latex conditions-of-satisfaction
        uses: xu-cheng/latex-action@v2
        with:
          root_file: "conditions-of-satisfaction.tex"
          working_directory: "conditions-of-satisfaction/"
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode -shell-escape
  
      - name: Compile latex domain-driven-development
        uses: xu-cheng/latex-action@v2
        with:
          root_file: "domain-driven-development.tex"
          working_directory: "domain-driven-development/"
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode -shell-escape
  
      - name: Compile latex project-overview-statement
        uses: xu-cheng/latex-action@v2
        with:
          root_file: "project-overview-statement.tex"
          working_directory: "project-overview-statement/"
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode -shell-escape
  
      - name: Compile latex risk-analysis
        uses: xu-cheng/latex-action@v2
        with:
          root_file: "risk-analysis.tex"
          working_directory: "risk-analysis/"
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode -shell-escape
  
      - name: Compile latex sprints
        uses: xu-cheng/latex-action@v2
        with:
          root_file: "sprints.tex"
          working_directory: "sprints/"
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode -shell-escape
  
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        run: |
          npm install
          npx semantic-release